version: '{build}'

<<<<<<< HEAD
=======
branches:
  only:
    - master
    - /ci.*/
    - /stable.*/

>>>>>>> libre_1.7.3
init:
  - ps: $env:commit = $env:appveyor_repo_commit.SubString(0,8)

install:
<<<<<<< HEAD
- ps: Install-Product node $env:NODE_VERSION
- ps: npm config set msvs_version 2015
=======
  - ps: Install-Product node $env:NODE_VERSION
  - ps: npm config set msvs_version 2015
>>>>>>> libre_1.7.3

build_script:
- cmd: npm install && npm run build
- cmd: node app/build/create-windows-installer.js

<<<<<<< HEAD
# Stop Appveyor from "Discovering Tests" forever 
=======
# Stop Appveyor from "Discovering Tests" forever
>>>>>>> libre_1.7.3
test: off

after_build:
  - ps: Get-ChildItem .\app\dist\*.tar.gz | % { Push-AppveyorArtifact $_.FullName -FileName "$($_.Name)" }
  - ps: Get-ChildItem .\app\dist\MailspringSetup.exe | % { Push-AppveyorArtifact $_.FullName -FileName "$($_.Name)" }
  - ps: Get-ChildItem .\app\dist\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName "$($_.Name)" }
  - ps: Get-ChildItem .\app\dist\RELEASES | % { Push-AppveyorArtifact $_.FullName -FileName "$($_.Name)" }

environment:
  matrix:
    - NODE_VERSION: '11'
  global:
    SIGN_BUILD: false

cache:
  - node_modules -> package.json
  - app\node_modules -> app\package.json