blank_issues_enabled: false
contact_links:
  - name: Mailspring Knowledge Base
    url: https://support.getmailspring.com
    about: If you're curious about how to use Mailspring or looking for instructions, you may find what you need in our knowledge base!
